# Generated by Django 5.1.4 on 2025-01-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Введите место выполнения привычки",
                        max_length=200,
                        null=True,
                        verbose_name="Место выполнения привычки",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        blank=True,
                        help_text="Укажите время выполнения привычки",
                        null=True,
                        verbose_name="Время выполнения привычки",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        help_text="Введите действие представляющее привычку",
                        max_length=200,
                        null=True,
                        verbose_name="Действие представляющее привычку",
                    ),
                ),
                (
                    "is_nice",
                    models.BooleanField(
                        default=False,
                        help_text="Введите признак приятной привычки",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        blank=True,
                        default=1,
                        help_text="Укажите периодичность выполнения привычки в днях",
                        null=True,
                        verbose_name="Периодичность выполнения привычки в днях",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Введите вознаграждение за выполнение привычки",
                        max_length=200,
                        null=True,
                        verbose_name="Вознаграждение за выполнение привычки",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True,
                        help_text="Введите продолжительность выполнения привычки",
                        null=True,
                        verbose_name="Продолжительность выполнения привычки",
                    ),
                ),
                (
                    "publicity",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Введите публичность привычки",
                        null=True,
                        verbose_name="Публичность привычки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Полезная привычка",
                "verbose_name_plural": "Полезные привычки",
            },
        ),
        migrations.CreateModel(
            name="NiceHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Введите действие приятной привычки",
                        max_length=300,
                        verbose_name="Действие приятной привычки",
                    ),
                ),
                (
                    "is_nice",
                    models.BooleanField(
                        default=True,
                        help_text="Введите признак приятной привычки",
                        null=True,
                        verbose_name="Признак приятной привычки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приятная привычка",
                "verbose_name_plural": "Приятные привычки",
            },
        ),
    ]
