# Generated by Django 5.1.4 on 2025-01-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="publicity",
            field=models.BooleanField(
                default=False,
                help_text="Введите публичность привычки",
                verbose_name="Публичность привычки",
            ),
        ),
    ]
